# Generated by Django 5.1.3 on 2024-11-23 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('co2_emissions', models.FloatField()),
                ('methane_emissions', models.FloatField()),
                ('coal_mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='mines.coalmine')),
            ],
        ),
    ]
