# Generated by Django 5.1.3 on 2024-12-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0004_emissionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonSink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine_location', models.CharField(choices=[('jharkhand', 'Jharkhand'), ('rajasthan', 'Rajasthan'), ('assam', 'Assam'), ('other', 'Other')], default='other', max_length=20)),
                ('forest_area_hectares', models.FloatField()),
                ('sequestration_rate', models.FloatField(blank=True, null=True)),
                ('total_sequestration', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excavation_tonnes', models.FloatField()),
                ('transportation_cost', models.FloatField()),
                ('fuel_usage_liters', models.FloatField()),
                ('electricity_usage_kwh', models.FloatField()),
                ('total_emissions_kg', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_value', models.FloatField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AfforestationPlan',
        ),
        migrations.DeleteModel(
            name='CarbonCreditRate',
        ),
        migrations.RemoveField(
            model_name='emission',
            name='coal_mine',
        ),
        migrations.DeleteModel(
            name='EmissionFactor',
        ),
        migrations.DeleteModel(
            name='EmissionResult',
        ),
        migrations.DeleteModel(
            name='Emission',
        ),
    ]
